import { Header } from "@/components/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className=" p-8 min-h-screen max-w-7xl mx-auto flex  justify-center overflow-hidden  ">
      <div className="absolute h-full w-full bg-[linear-gradient(to_right,#b1b1b12e_1px,transparent_1px),linear-gradient(to_bottom,#b1b1b12e_1px,transparent_1px)] bg-[size:14px_24px] [mask-image:radial-gradient(ellipse_30%_50%_at_20%_80%,#000_10%,transparent_100%)]" />
      <div className="w-full h-full">
        <Header />
        {children}
      </div>
    </main>
  );
}
